### ISSUE TITLE
Issue running tests on latest Geth 1.13.0

### ISSUE THREAD

**Issue by arddluma** [eth-infinitism/bundler-spec-tests#37]
Compliance tests do not work with latest [Geth 1.13.0 release](https://github.com/ethereum/go-ethereum/releases/tag/v1.13.0)

```
FAILED tests/bundle/test_codehash.py::test_codehash_changed[] - AssertionError: could not create account with a different codehash
assert '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470' != '0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470'
```

Failed CI run on Skandha bundler: https://github.com/etherspot/skandha/actions/runs/6160886035/job/16719407282
Failed CI run on Stackup bundler: https://github.com/stackup-wallet/stackup-bundler/actions/runs/6219516263/job/16877738642

Note: Works fine with previous versions such as 1.12.2

**Comment by shahafn** [comment]
Hi @arddluma thanks for letting us know, we'll take a look at it and update here!

**Comment by shahafn** [comment]
Fixed
