### ISSUE TITLE
Test failed due to letter case not matching in userOp

### ISSUE THREAD

**Issue by tongshi** [eth-infinitism/bundler-spec-tests#55]
When testing, I have some tests in `test_bundler` failed due to letter case not matching in userOp.initCode.
It would be better if tests can support case insensitive comparison of userOp, as letter case in hex string is not important. 
Have opened a pr for this, thank you.
https://github.com/eth-infinitism/bundler-spec-tests/pull/54

**Comment by drortirosh** [comment]
fixed
